#!/usr/bin/env ruby
require 'rubygems'
gem 'activerecord', '2.3.5'
require 'yaml'

require File.expand_path('lib/source_generator', File.dirname(__FILE__))

CONFIG_FILE = ARGV.shift || "db2sgen.yml"
config = YAML.load File.read(CONFIG_FILE) 

SourceGenerator.new(config).generate
